import { AppSettings, Game, System } from '../types';

export const DEMO_SYSTEMS: System[] = [
  { id: 'windows', name: 'Windows PC Games', short_name: 'PC Games', manufacturer: 'Microsoft', extensions: ['exe'], icon: 'monitor', default_emulator_id: 'native', folder_names: ['windows', 'pc'] },
  { id: 'arcade', name: 'Arcade (MAME / FBNeo)', short_name: 'Arcade', manufacturer: 'Arcade', extensions: ['zip', '7z'], icon: 'flame', default_emulator_id: 'retroarch', folder_names: ['arcade', 'mame', 'fbneo'] },
  { id: 'nes', name: 'Nintendo Entertainment System', short_name: 'NES', manufacturer: 'Nintendo', extensions: ['nes', 'zip'], icon: 'gamepad-2', default_emulator_id: 'retroarch', folder_names: ['nes'] },
  { id: 'snes', name: 'Super Nintendo Entertainment System', short_name: 'Super Nintendo', manufacturer: 'Nintendo', extensions: ['sfc', 'smc', 'zip'], icon: 'gamepad-2', default_emulator_id: 'retroarch', folder_names: ['snes'] },
  { id: 'n64', name: 'Nintendo 64', short_name: 'Nintendo 64', manufacturer: 'Nintendo', extensions: ['z64', 'n64', 'v64'], icon: 'box', default_emulator_id: 'retroarch', folder_names: ['n64'] },
  { id: 'gb', name: 'Game Boy / Game Boy Color', short_name: 'Game Boy', manufacturer: 'Nintendo', extensions: ['gb', 'gbc', 'zip'], icon: 'smartphone', default_emulator_id: 'retroarch', folder_names: ['gb', 'gbc'] },
  { id: 'gba', name: 'Game Boy Advance', short_name: 'GBA', manufacturer: 'Nintendo', extensions: ['gba', 'zip'], icon: 'smartphone', default_emulator_id: 'retroarch', folder_names: ['gba'] },
  { id: 'gamecube', name: 'Nintendo GameCube', short_name: 'GameCube', manufacturer: 'Nintendo', extensions: ['iso', 'gcm', 'ciso'], icon: 'disc', default_emulator_id: 'dolphin', folder_names: ['gamecube', 'gc'] },
  { id: 'wii', name: 'Nintendo Wii', short_name: 'Wii', manufacturer: 'Nintendo', extensions: ['wbfs', 'iso'], icon: 'disc', default_emulator_id: 'dolphin', folder_names: ['wii'] },
  { id: 'switch', name: 'Nintendo Switch', short_name: 'Switch', manufacturer: 'Nintendo', extensions: ['nsp', 'xci'], icon: 'toggle-right', default_emulator_id: 'ryujinx', folder_names: ['switch'] },
  { id: 'megadrive', name: 'Sega Mega Drive / Genesis', short_name: 'Mega Drive', manufacturer: 'Sega', extensions: ['md', 'bin', 'gen', 'zip'], icon: 'radio', default_emulator_id: 'retroarch', folder_names: ['megadrive', 'genesis'] },
  { id: 'dreamcast', name: 'Sega Dreamcast', short_name: 'Dreamcast', manufacturer: 'Sega', extensions: ['cdi', 'gdi', 'chd'], icon: 'disc', default_emulator_id: 'retroarch', folder_names: ['dreamcast'] },
  { id: 'ps1', name: 'Sony PlayStation', short_name: 'PlayStation', manufacturer: 'Sony', extensions: ['cue', 'chd', 'iso', 'pbp'], icon: 'disc', default_emulator_id: 'retroarch', folder_names: ['ps1', 'psx'] },
  { id: 'ps2', name: 'Sony PlayStation 2', short_name: 'PlayStation 2', manufacturer: 'Sony', extensions: ['iso', 'chd'], icon: 'disc', default_emulator_id: 'pcsx2', folder_names: ['ps2'] },
  { id: 'ps3', name: 'Sony PlayStation 3', short_name: 'PlayStation 3', manufacturer: 'Sony', extensions: ['iso', 'pkg'], icon: 'disc', default_emulator_id: 'native', folder_names: ['ps3'] },
];

export const DEMO_GAMES: Game[] = [
  // 1. STREET FIGHTER II (Hero Featured Showcase Game)
  {
    id: 'sf2-champ',
    system_id: 'arcade',
    title: 'STREET FIGHTER II',
    original_title: 'CHAMPION EDITION',
    file_path: 'D:\\Roms\\arcade\\sf2ce.zip',
    file_name: 'sf2ce.zip',
    file_size: 8388608,
    franchise: 'Street Fighter',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r2s.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc7xvd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc7xvd.jpg',
      'https://images.igdb.com/igdb/image/upload/t_720p/sc7xvc.jpg',
      'https://images.igdb.com/igdb/image/upload/t_720p/sc7xvb.jpg',
      'https://images.igdb.com/igdb/image/upload/t_720p/sc7xva.jpg',
    ],
    genre: 'Combat / Versus Arcade',
    developer: 'Capcom',
    publisher: 'Capcom',
    release_date: '1992',
    rating: 4.8,
    players: 2,
    favorite: true,
    hidden: false,
    featured: true,
    play_count: 126,
    play_time_seconds: 18400,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis:
      'Le jeu de combat légendaire qui a révolutionné l\'arcade. Choisissez votre combattant parmi les 8 World Warriors et les 4 Grand Masters et devenez le champion du monde !',
  },

  // 2. METAL SLUG 3
  {
    id: 'mslug3',
    system_id: 'arcade',
    title: 'METAL SLUG 3',
    original_title: 'Metal Slug 3 (Neo Geo MVS)',
    file_path: 'D:\\Roms\\arcade\\mslug3.zip',
    file_name: 'mslug3.zip',
    file_size: 78643200,
    franchise: 'Metal Slug',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x3k.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc7yud.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc7yud.jpg',
      'https://images.igdb.com/igdb/image/upload/t_720p/sc7yue.jpg',
    ],
    genre: 'Run and Gun / Arcade',
    developer: 'SNK',
    publisher: 'SNK',
    release_date: '1999',
    rating: 4.7,
    players: 2,
    favorite: true,
    hidden: false,
    featured: true,
    play_count: 48,
    play_time_seconds: 9200,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'L\'apogée de la saga Neo-Geo avec des embranchements multiples, des zombies, des extraterrestres et une action frénétique sans temps mort.',
  },

  // 3. SONIC THE HEDGEHOG 2
  {
    id: 'sonic2',
    system_id: 'megadrive',
    title: 'SONIC THE HEDGEHOG 2',
    original_title: 'Sonic The Hedgehog 2',
    file_path: 'D:\\Roms\\megadrive\\Sonic2.bin',
    file_name: 'Sonic2.bin',
    file_size: 1048576,
    franchise: 'Sonic',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2243.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc68vd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc68vd.jpg',
      'https://images.igdb.com/igdb/image/upload/t_720p/sc68ve.jpg',
    ],
    genre: 'Plateforme / Vitesse',
    developer: 'Sonic Team / STI',
    publisher: 'Sega',
    release_date: '1992',
    rating: 4.8,
    players: 2,
    favorite: true,
    hidden: false,
    featured: true,
    play_count: 35,
    play_time_seconds: 7800,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Foncez à toute vitesse avec Sonic et Tails pour contrecarrer les plans du Dr. Robotnik et de son Death Egg.',
  },

  // 4. THE LEGEND OF ZELDA: A LINK TO THE PAST
  {
    id: 'zelda-alttp',
    system_id: 'snes',
    title: 'THE LEGEND OF ZELDA',
    original_title: 'A Link to the Past',
    file_path: 'D:\\Roms\\snes\\Zelda - A Link to the Past.sfc',
    file_name: 'Zelda - A Link to the Past.sfc',
    file_size: 2097152,
    franchise: 'The Legend of Zelda',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r8c.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc7xwe.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc7xwe.jpg',
      'https://images.igdb.com/igdb/image/upload/t_720p/sc7xwf.jpg',
    ],
    genre: 'Aventure / Action-RPG',
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    release_date: '1991',
    rating: 4.9,
    players: 1,
    favorite: true,
    hidden: false,
    featured: true,
    play_count: 52,
    play_time_seconds: 24000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Explorez le Royaume de la Lumière et les Ténèbres pour sauver les sept jeunes filles et vaincre Ganon.',
  },

  // 5. TEKKEN 3
  {
    id: 'tekken3',
    system_id: 'ps1',
    title: 'TEKKEN 3',
    original_title: 'Tekken 3 (PlayStation)',
    file_path: 'D:\\Roms\\ps1\\Tekken 3.chd',
    file_name: 'Tekken 3.chd',
    file_size: 524288000,
    franchise: 'Street Fighter & Tekken',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co20ex.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc7zwe.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc7zwe.jpg',
    ],
    genre: 'Combat 3D',
    developer: 'Namco',
    publisher: 'Namco',
    release_date: '1997',
    rating: 4.8,
    players: 2,
    favorite: true,
    hidden: false,
    featured: true,
    play_count: 89,
    play_time_seconds: 14200,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Le chef d\'œuvre du combat 3D 32-bit avec Jin Kazama, Hwoarang, Eddy Gordo et Xiaoyu.',
  },

  // 6. RESIDENT EVIL 2
  {
    id: 're2',
    system_id: 'ps1',
    title: 'RESIDENT EVIL 2',
    original_title: 'Resident Evil 2 (DualShock Edition)',
    file_path: 'D:\\Roms\\ps1\\Resident Evil 2.chd',
    file_name: 'Resident Evil 2.chd',
    file_size: 734003200,
    franchise: 'Resident Evil',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x76.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc8axd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc8axd.jpg',
    ],
    genre: 'Survival Horror',
    developer: 'Capcom',
    publisher: 'Capcom',
    release_date: '1998',
    rating: 4.8,
    players: 1,
    favorite: true,
    hidden: false,
    featured: true,
    play_count: 24,
    play_time_seconds: 16000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Survivez à l\'épidémie du virus T dans le commissariat de Raccoon City avec Leon S. Kennedy et Claire Redfield.',
  },

  // 7. MARVEL VS. CAPCOM 2
  {
    id: 'mvc2',
    system_id: 'arcade',
    title: 'MARVEL VS. CAPCOM 2',
    original_title: 'New Age of Heroes',
    file_path: 'D:\\Roms\\arcade\\mvsc2.zip',
    file_name: 'mvsc2.zip',
    file_size: 188743680,
    franchise: 'Capcom Versus',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rc9.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc8bxd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc8bxd.jpg',
    ],
    genre: 'Combat 3v3 / Arcade',
    developer: 'Capcom',
    publisher: 'Capcom',
    release_date: '2000',
    rating: 4.7,
    players: 2,
    favorite: true,
    hidden: false,
    featured: true,
    play_count: 67,
    play_time_seconds: 11200,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Le cross-over légendaire à 56 personnages avec des combos aériens dévastateurs en 3 contre 3.',
  },

  // 8. RAYMAN 2: THE GREAT ESCAPE
  {
    id: 'rayman2',
    system_id: 'n64',
    title: 'RAYMAN 2',
    original_title: 'The Great Escape',
    file_path: 'D:\\Roms\\n64\\Rayman2.z64',
    file_name: 'Rayman2.z64',
    file_size: 33554432,
    franchise: 'Rayman',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2044.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc8cxd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc8cxd.jpg',
    ],
    genre: 'Plateforme 3D / Aventure',
    developer: 'Ubisoft Montpellier',
    publisher: 'Ubisoft',
    release_date: '1999',
    rating: 4.5,
    players: 1,
    favorite: false,
    hidden: false,
    play_count: 18,
    play_time_seconds: 6400,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Libérez la Croisée des Rêves des pirates robots de l\'amiral Barbe-Tranchante.',
  },

  // 9. PAC-MAN
  {
    id: 'pacman',
    system_id: 'arcade',
    title: 'PAC-MAN',
    original_title: 'Pac-Man (Midway)',
    file_path: 'D:\\Roms\\arcade\\pacman.zip',
    file_name: 'pacman.zip',
    file_size: 65536,
    franchise: 'Pac-Man',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7e.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc8dxd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc8dxd.jpg',
    ],
    genre: 'Arcade / Labyrinthe',
    developer: 'Namco',
    publisher: 'Namco',
    release_date: '1980',
    rating: 4.6,
    players: 2,
    favorite: true,
    hidden: false,
    play_count: 42,
    play_time_seconds: 3200,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Dévorez toutes les pac-gommes en évitant Blinky, Pinky, Inky et Clyde dans ce monument de l\'histoire.',
  },

  // 10. DOOM
  {
    id: 'doom',
    system_id: 'windows',
    title: 'DOOM',
    original_title: 'The Ultimate DOOM',
    file_path: 'D:\\Roms\\windows\\DOOM.exe',
    file_name: 'DOOM.exe',
    file_size: 15728640,
    franchise: 'Doom',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x79.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc8exd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc8exd.jpg',
    ],
    genre: 'FPS / Action',
    developer: 'id Software',
    publisher: 'GT Interactive',
    release_date: '1993',
    rating: 4.8,
    players: 1,
    favorite: true,
    hidden: false,
    play_count: 36,
    play_time_seconds: 8800,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Incarnez le Doom Slayer et anéantissez les hordes démoniaques sur les bases de Phobos et Deimos.',
  },

  // 11. CRASH BANDICOOT
  {
    id: 'crash1',
    system_id: 'ps1',
    title: 'CRASH BANDICOOT',
    original_title: 'Crash Bandicoot 3: Warped',
    file_path: 'D:\\Roms\\ps1\\Crash3.chd',
    file_name: 'Crash3.chd',
    file_size: 471859200,
    franchise: 'Crash Bandicoot',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co204b.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc8fxd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc8fxd.jpg',
    ],
    genre: 'Plateforme 3D',
    developer: 'Naughty Dog',
    publisher: 'Sony',
    release_date: '1998',
    rating: 4.7,
    players: 1,
    favorite: true,
    hidden: false,
    play_count: 27,
    play_time_seconds: 7500,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Voyagez à travers le temps avec Crash et Coco pour contrecarrer les plans d\'Uka Uka et Neo Cortex.',
  },

  // 12. F-ZERO X
  {
    id: 'fzero-x',
    system_id: 'n64',
    title: 'F-ZERO X',
    original_title: 'F-Zero X (Nintendo 64)',
    file_path: 'D:\\Roms\\n64\\FZeroX.z64',
    file_name: 'FZeroX.z64',
    file_size: 16777216,
    franchise: 'F-Zero',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7c.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc8gxd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc8gxd.jpg',
    ],
    genre: 'Course Futuriste / 60 FPS',
    developer: 'Nintendo EAD',
    publisher: 'Nintendo',
    release_date: '1998',
    rating: 4.6,
    players: 4,
    favorite: false,
    hidden: false,
    play_count: 19,
    play_time_seconds: 4600,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Des courses ultra-rapides à 30 véhicules simultanés à 60 images par seconde avec bande-son hard rock.',
  },

  // 13. BOMBERMAN '94
  {
    id: 'bomberman94',
    system_id: 'arcade',
    title: 'BOMBERMAN \'94',
    original_title: 'Bomberman \'94 / Mega Bomberman',
    file_path: 'D:\\Roms\\arcade\\bbman94.zip',
    file_name: 'bbman94.zip',
    file_size: 2097152,
    franchise: 'Bomberman',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7b.png',
    backdrop_url: 'https://images.igdb.com/igdb/image/upload/t_1080p/sc8hxd.jpg',
    screenshots: [
      'https://images.igdb.com/igdb/image/upload/t_720p/sc8hxd.jpg',
    ],
    genre: 'Action / Party Game',
    developer: 'Hudson Soft',
    publisher: 'Hudson Soft',
    release_date: '1994',
    rating: 4.4,
    players: 5,
    favorite: false,
    hidden: false,
    play_count: 14,
    play_time_seconds: 3900,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Posez vos bombes, chevauchez les kangourous Louies et éliminez tous vos rivaux en multijoueur.',
  },
];

export const DEFAULT_APP_SETTINGS: AppSettings = {
  fullscreen: false,
  always_on_top: false,
  kiosk_mode: false,
  game_select_action: 'details',
  enabled_franchises: ['mario', 'zelda', 'pokemon', 'sonic', 'versus', 'rpg'],
  custom_franchises: [],
  theme: 'retro-80s-light',
};
