import { AppSettings, Game, System } from '../types';

export const DEMO_SYSTEMS: System[] = [
  { id: 'snes', name: 'Super Nintendo', short_name: 'SNES', manufacturer: 'Nintendo', extensions: ['sfc'], icon: 'gamepad-2', default_emulator_id: 'retroarch', folder_names: ['snes'] },
  { id: 'ps1', name: 'PlayStation', short_name: 'PS1', manufacturer: 'Sony', extensions: ['cue', 'chd'], icon: 'disc', default_emulator_id: 'retroarch', folder_names: ['ps1'] },
  { id: 'n64', name: 'Nintendo 64', short_name: 'N64', manufacturer: 'Nintendo', extensions: ['z64'], icon: 'box', default_emulator_id: 'retroarch', folder_names: ['n64'] },
  { id: 'switch', name: 'Nintendo Switch', short_name: 'Switch', manufacturer: 'Nintendo', extensions: ['nsp', 'xci'], icon: 'toggle-right', default_emulator_id: 'ryujinx', folder_names: ['switch'] },
  { id: 'ps2', name: 'PlayStation 2', short_name: 'PS2', manufacturer: 'Sony', extensions: ['iso', 'chd'], icon: 'disc', default_emulator_id: 'pcsx2', folder_names: ['ps2'] },
  { id: 'arcade', name: 'Arcade (MAME)', short_name: 'Arcade', manufacturer: 'Arcade', extensions: ['zip'], icon: 'joystick', default_emulator_id: 'retroarch', folder_names: ['arcade'] },
  { id: 'windows', name: 'PC Games Windows', short_name: 'PC Games', manufacturer: 'Microsoft', extensions: ['exe'], icon: 'monitor', default_emulator_id: 'native', folder_names: ['windows'] },
];

export const DEMO_GAMES: Game[] = [
  {
    id: 'demo-1',
    system_id: 'snes',
    title: 'Super Mario World',
    file_path: 'D:\\Roms\\snes\\Super Mario World.sfc',
    file_name: 'Super Mario World.sfc',
    file_size: 1048576,
    franchise: 'Super Mario',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1x7d.png',
    genre: 'Plateforme',
    developer: 'Nintendo EAD',
    release_date: '1990-11-21',
    rating: 4.9,
    favorite: true,
    hidden: false,
    play_count: 14,
    play_time_seconds: 4800,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Mario et Yoshi parcourent Dinosaur Land pour délivrer Peach et battre Bowser.',
  },
  {
    id: 'demo-2',
    system_id: 'snes',
    title: 'Super Mario Kart',
    file_path: 'D:\\Roms\\snes\\Super Mario Kart.sfc',
    file_name: 'Super Mario Kart.sfc',
    file_size: 1048576,
    franchise: 'Super Mario',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r2h.png',
    genre: 'Course',
    developer: 'Nintendo EAD',
    release_date: '1992-08-27',
    rating: 4.7,
    favorite: true,
    hidden: false,
    play_count: 22,
    play_time_seconds: 6200,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Le premier Mario Kart légendaire avec le Mode 7 de la Super Nintendo.',
  },
  {
    id: 'demo-3',
    system_id: 'snes',
    title: 'The Legend of Zelda: A Link to the Past',
    file_path: 'D:\\Roms\\snes\\Zelda - A Link to the Past.sfc',
    file_name: 'Zelda - A Link to the Past.sfc',
    file_size: 2097152,
    franchise: 'The Legend of Zelda',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r8c.png',
    genre: 'Aventure / Action-RPG',
    developer: 'Nintendo',
    release_date: '1991-11-21',
    rating: 5.0,
    favorite: true,
    hidden: false,
    play_count: 9,
    play_time_seconds: 12000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Link explore Hyrule et le Monde des Ténèbres pour sceller Ganon.',
  },
  {
    id: 'demo-4',
    system_id: 'ps1',
    title: 'Tekken 3',
    file_path: 'D:\\Roms\\ps1\\Tekken 3.chd',
    file_name: 'Tekken 3.chd',
    file_size: 524288000,
    franchise: 'Street Fighter & Tekken',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co20ex.png',
    genre: 'Combat / Versus',
    developer: 'Namco',
    release_date: '1998-03-26',
    rating: 4.8,
    favorite: true,
    hidden: false,
    play_count: 31,
    play_time_seconds: 9400,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Le roi des jeux de combat 3D PlayStation.',
  },
  {
    id: 'demo-5',
    system_id: 'arcade',
    title: 'Street Fighter II - Champion Edition',
    file_path: 'D:\\Roms\\arcade\\sf2ce.zip',
    file_name: 'sf2ce.zip',
    file_size: 8388608,
    franchise: 'Street Fighter & Tekken',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r2s.png',
    genre: 'Combat / Arcade',
    developer: 'Capcom',
    release_date: '1992-03-13',
    rating: 4.9,
    favorite: false,
    hidden: false,
    play_count: 18,
    play_time_seconds: 5400,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: "L'icône absolue des salles d'arcade 80s/90s.",
  },
  {
    id: 'demo-6',
    system_id: 'n64',
    title: 'Super Mario 64',
    file_path: 'D:\\Roms\\n64\\Super Mario 64.z64',
    file_name: 'Super Mario 64.z64',
    file_size: 8388608,
    franchise: 'Super Mario',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1w2y.png',
    genre: 'Plateforme 3D',
    developer: 'Nintendo',
    release_date: '1996-06-23',
    rating: 4.9,
    favorite: true,
    hidden: false,
    play_count: 15,
    play_time_seconds: 7000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: 'Le jeu qui a défini la 3D.',
  },
  {
    id: 'demo-7',
    system_id: 'switch',
    title: 'Super Mario Odyssey',
    file_path: 'D:\\Roms\\switch\\Super Mario Odyssey.nsp',
    file_name: 'Super Mario Odyssey.nsp',
    file_size: 5700000000,
    franchise: 'Super Mario',
    cover_url: 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1m1o.png',
    genre: 'Plateforme 3D',
    developer: 'Nintendo EPD',
    release_date: '2017-10-27',
    rating: 4.9,
    favorite: false,
    hidden: false,
    play_count: 6,
    play_time_seconds: 18000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    synopsis: "Explorez d'immenses royaumes 3D avec Cappy.",
  },
];

export const DEFAULT_APP_SETTINGS: AppSettings = {
  fullscreen: false,
  always_on_top: false,
  kiosk_mode: false,
  enabled_franchises: ['mario', 'zelda', 'pokemon', 'sonic', 'versus', 'rpg'],
  custom_franchises: [],
  theme: 'retro-80s-light',
};
