import { ControllerType, GamepadMapping, RemapStep } from '../types';

export const DEFAULT_GAMEPAD_MAPPING = (playerIndex: number): GamepadMapping => ({
  player_index: playerIndex,
  physical_joypad_index: playerIndex,
  device_name: `Contrôleur Joueur ${playerIndex + 1}`,
  device_id: `pad_${playerIndex}`,
  controller_type: 'arcade_stick',
  btn_up: 'up',
  btn_down: 'down',
  btn_left: 'left',
  btn_right: 'right',
  btn_a: '0',
  btn_b: '1',
  btn_x: '2',
  btn_y: '3',
  btn_l1: '4',
  btn_r1: '5',
  btn_l2: '6',
  btn_r2: '7',
  btn_select: '8',
  btn_start: '9',
  btn_hotkey: '8',
  deadzone: 0.15,
});

export const REMAP_STEPS_BY_TYPE: Record<ControllerType, RemapStep[]> = {
  arcade_stick: [
    { key: 'btn_a', label: 'BOUTON 1 (A / Valider)', icon: '🔴', desc: 'Bouton 1 de votre borne arcade' },
    { key: 'btn_b', label: 'BOUTON 2 (B / Retour)', icon: '🔵', desc: 'Bouton 2 de votre borne arcade' },
    { key: 'btn_x', label: 'BOUTON 3 (X / Menu)', icon: '🟡', desc: 'Bouton 3 (Menu avec Coin)' },
    { key: 'btn_y', label: 'BOUTON 4 (Y)', icon: '🟢', desc: 'Bouton 4 de votre borne arcade' },
    { key: 'btn_l1', label: 'BOUTON 5 (L1)', icon: '🟣', desc: 'Bouton 5 de votre borne arcade' },
    { key: 'btn_r1', label: 'BOUTON 6 (R1)', icon: '🟠', desc: 'Bouton 6 de votre borne arcade' },
    { key: 'btn_select', label: 'COIN / CRÉDIT 🪙', icon: '🪙', desc: 'Insérer Pièce (Maintenir avec Start pour Quitter)' },
    { key: 'btn_start', label: 'START 🕹️ (Lancer)', icon: '🚀', desc: 'Lancer Partie (Appuyer avec Coin pour Quitter)' },
    { key: 'btn_up', label: 'JOYSTICK HAUT', icon: '⬆️', desc: 'Poussez le joystick vers le haut' },
    { key: 'btn_down', label: 'JOYSTICK BAS', icon: '⬇️', desc: 'Poussez le joystick vers le bas' },
    { key: 'btn_left', label: 'JOYSTICK GAUCHE', icon: '⬅️', desc: 'Poussez le joystick vers la gauche' },
    { key: 'btn_right', label: 'JOYSTICK DROITE', icon: '➡️', desc: 'Poussez le joystick vers la droite' },
  ],
  standard: [
    { key: 'btn_a', label: 'BOUTON A (Croix / Valider)', icon: '🟢', desc: 'Bouton A (Xbox) ou Croix (PlayStation)' },
    { key: 'btn_b', label: 'BOUTON B (Rond / Retour)', icon: '🔴', desc: 'Bouton B (Xbox) ou Rond (PlayStation)' },
    { key: 'btn_x', label: 'BOUTON X (Carré)', icon: '🔵', desc: 'Bouton X (Xbox) ou Carré (PlayStation)' },
    { key: 'btn_y', label: 'BOUTON Y (Triangle)', icon: '🟡', desc: 'Bouton Y (Xbox) ou Triangle (PlayStation)' },
    { key: 'btn_l1', label: 'GÂCHETTE LB / L1', icon: '🔘', desc: 'Bouton supérieur gauche' },
    { key: 'btn_r1', label: 'GÂCHETTE RB / R1', icon: '🔘', desc: 'Bouton supérieur droit' },
    { key: 'btn_l2', label: 'GÂCHETTE LT / L2', icon: '⚡', desc: 'Gâchette basse gauche' },
    { key: 'btn_r2', label: 'GÂCHETTE RT / R2', icon: '⚡', desc: 'Gâchette basse droite' },
    { key: 'btn_select', label: 'SELECT / BACK / VIEW', icon: '⬅️', desc: 'Touche Select ou View' },
    { key: 'btn_start', label: 'START / MENU', icon: '▶️', desc: 'Touche Start ou Options' },
    { key: 'btn_hotkey', label: 'BOUTON GUIDE / HOTKEY', icon: '🏠', desc: 'Bouton central Xbox/PS' },
    { key: 'btn_up', label: 'D-PAD HAUT', icon: '⬆️', desc: 'Croix directionnelle Haut' },
    { key: 'btn_down', label: 'D-PAD BAS', icon: '⬇️', desc: 'Croix directionnelle Bas' },
    { key: 'btn_left', label: 'D-PAD GAUCHE', icon: '⬅️', desc: 'Croix directionnelle Gauche' },
    { key: 'btn_right', label: 'D-PAD DROITE', icon: '➡️', desc: 'Croix directionnelle Droite' },
  ],
  retro_snes: [
    { key: 'btn_b', label: 'BOUTON B (Bas)', icon: '🟣', desc: 'Bouton B inférieur' },
    { key: 'btn_a', label: 'BOUTON A (Droite)', icon: '🟣', desc: 'Bouton A droit' },
    { key: 'btn_y', label: 'BOUTON Y (Gauche)', icon: '⚪', desc: 'Bouton Y gauche' },
    { key: 'btn_x', label: 'BOUTON X (Haut)', icon: '⚪', desc: 'Bouton X supérieur' },
    { key: 'btn_l1', label: 'BOUTON L', icon: '🔘', desc: 'Gâchette L' },
    { key: 'btn_r1', label: 'BOUTON R', icon: '🔘', desc: 'Gâchette R' },
    { key: 'btn_select', label: 'SELECT', icon: '➖', desc: 'Bouton Select' },
    { key: 'btn_start', label: 'START', icon: '➕', desc: 'Bouton Start' },
    { key: 'btn_up', label: 'CROIX HAUT', icon: '⬆️', desc: 'D-Pad Haut' },
    { key: 'btn_down', label: 'CROIX BAS', icon: '⬇️', desc: 'D-Pad Bas' },
    { key: 'btn_left', label: 'CROIX GAUCHE', icon: '⬅️', desc: 'D-Pad Gauche' },
    { key: 'btn_right', label: 'CROIX DROITE', icon: '➡️', desc: 'D-Pad Droite' },
  ],
  retro_sega: [
    { key: 'btn_a', label: 'BOUTON A', icon: '⚪', desc: 'Bouton A inférieur gauche' },
    { key: 'btn_b', label: 'BOUTON B', icon: '⚪', desc: 'Bouton B inférieur milieu' },
    { key: 'btn_l1', label: 'BOUTON C', icon: '⚪', desc: 'Bouton C inférieur droit' },
    { key: 'btn_x', label: 'BOUTON X', icon: '⚫', desc: 'Bouton X supérieur gauche' },
    { key: 'btn_y', label: 'BOUTON Y', icon: '⚫', desc: 'Bouton Y supérieur milieu' },
    { key: 'btn_r1', label: 'BOUTON Z', icon: '⚫', desc: 'Bouton Z supérieur droit' },
    { key: 'btn_select', label: 'MODE', icon: '🔘', desc: 'Bouton Mode' },
    { key: 'btn_start', label: 'START', icon: '🔴', desc: 'Bouton Start' },
    { key: 'btn_up', label: 'CROIX HAUT', icon: '⬆️', desc: 'D-Pad Haut' },
    { key: 'btn_down', label: 'CROIX BAS', icon: '⬇️', desc: 'D-Pad Bas' },
    { key: 'btn_left', label: 'CROIX GAUCHE', icon: '⬅️', desc: 'D-Pad Gauche' },
    { key: 'btn_right', label: 'CROIX DROITE', icon: '➡️', desc: 'D-Pad Droite' },
  ],
  wheel: [
    { key: 'btn_left', label: 'VOLANT GAUCHE', icon: '↩️', desc: 'Tournez le volant vers la gauche' },
    { key: 'btn_right', label: 'VOLANT DROITE', icon: '↪️', desc: 'Tournez le volant vers la droite' },
    { key: 'btn_r2', label: 'ACCÉLÉRATEUR', icon: '🏎️', desc: 'Pédale d’accélérateur' },
    { key: 'btn_l2', label: 'FREIN', icon: '🛑', desc: 'Pédale de frein' },
    { key: 'btn_l1', label: 'PALETTE GAUCHE (Rétrograder)', icon: '🔻', desc: 'Palette gauche' },
    { key: 'btn_r1', label: 'PALETTE DROITE (Monter)', icon: '🔺', desc: 'Palette droite' },
    { key: 'btn_start', label: 'START', icon: '▶️', desc: 'Bouton Start' },
  ],
};

export const CONTROLLER_PROFILES: { id: ControllerType; label: string; desc: string }[] = [
  { id: 'arcade_stick', label: '🕹️ Borne / Stick Arcade', desc: '6 ou 8 boutons de borne' },
  { id: 'standard', label: '🎮 Manette Moderne', desc: 'Xbox Series / One / PS4 / PS5' },
  { id: 'retro_snes', label: '🕹️ Rétro SNES / NES', desc: 'Croix + 4 Boutons A/B/X/Y' },
  { id: 'retro_sega', label: '🕹️ Rétro Mega Drive', desc: 'Croix + 6 Boutons A/B/C/X/Y/Z' },
];
