export const SYSTEM_ICON_MAP: Record<string, string> = {
  windows: 'monitor',
  arcade: 'flame',
  nes: 'gamepad-2',
  snes: 'gamepad-2',
  n64: 'box',
  gb: 'smartphone',
  gbc: 'smartphone',
  gba: 'smartphone',
  gamecube: 'disc',
  wii: 'disc',
  switch: 'toggle-right',
  megadrive: 'radio',
  genesis: 'radio',
  dreamcast: 'disc',
  ps1: 'disc',
  ps2: 'disc',
  ps3: 'disc',
  ps4: 'disc',
  ps5: 'disc',
};
